Một vụ tranh chấp đáng chú ý liên quan đến giấy phép mã nguồn mở là vụ Software Freedom Conservancy (SFC) kiện Vizio, Inc. tại Hoa Kỳ. Vụ việc bắt đầu vào tháng 10 năm 2021 tại Tòa Thượng thẩm Quận Orange, California. SFC là một tổ chức phi lợi nhuận hoạt động nhằm bảo vệ quyền của người sử dụng phần mềm tự do và mã nguồn mở, trong khi Vizio là một công ty sản xuất TV. SFC mua một số TV thông minh của Vizio và cho rằng các thiết bị này sử dụng nhiều thành phần phần mềm mã nguồn mở được cấp phép theo GNU General Public License version 2 (GPLv2) và GNU Lesser General Public License version 2.1 (LGPLv2.1).

Vấn đề pháp lý chính là nghĩa vụ của Vizio khi phân phối sản phẩm có chứa phần mềm GPL và LGPL. GPL là một giấy phép copyleft, cho phép người dùng sử dụng, nghiên cứu, sửa đổi và phân phối phần mềm. Tuy nhiên, khi phân phối phần mềm thuộc phạm vi của GPL, bên phân phối phải tuân thủ các điều kiện của giấy phép, trong đó có nghĩa vụ cung cấp complete corresponding source code (mã nguồn tương ứng đầy đủ) theo những điều kiện được quy định. SFC cho rằng Vizio đã không cung cấp đầy đủ mã nguồn của các thành phần GPL/LGPL được sử dụng trong firmware của TV, mặc dù SFC đã yêu cầu.

Điểm đặc biệt của vụ án là SFC không khởi kiện với tư cách chủ sở hữu bản quyền của mã nguồn mà cho rằng mình có quyền với tư cách third-party beneficiary (bên thụ hưởng thứ ba) của thỏa thuận GPL. SFC muốn tòa án xác nhận rằng người mua sản phẩm chứa phần mềm GPL cũng có thể yêu cầu nhà sản xuất cung cấp mã nguồn tương ứng. Vizio đã phản đối quan điểm này và vụ án từng được chuyển lên tòa án liên bang. Tuy nhiên, vào tháng 5 năm 2022, tòa án liên bang đã quyết định đưa vụ việc trở lại Tòa Thượng thẩm California.

Đến tháng 1 năm 2024, thẩm phán tại California bác yêu cầu summary judgment của Vizio, cho phép vụ án tiếp tục. Tòa cũng xác định rằng yêu cầu của SFC về việc thực thi nghĩa vụ theo hợp đồng GPL không bị luật bản quyền liên bang ngăn cản.

Vụ việc có ý nghĩa pháp lý quan trọng vì cho thấy việc sử dụng phần mềm mã nguồn mở không đồng nghĩa với việc doanh nghiệp được sử dụng mà không phải tuân thủ giấy phép. Đặc biệt, các giấy phép copyleft như GPL có thể tạo ra những nghĩa vụ cụ thể đối với bên phân phối. Vụ Vizio cũng đặt ra câu hỏi về việc người sử dụng sản phẩm có quyền trực tiếp yêu cầu thực hiện các nghĩa vụ của GPL hay không. Tính đến năm 2026, vụ án vẫn đang tiếp diễn, vì vậy chưa có phán quyết cuối cùng về toàn bộ tranh chấp.
